### ISSUE TITLE
Using vrld's shine shaders with push

### ISSUE THREAD

**Issue by cooljith91112** [Ulydev/push#1]
How can I apply chained vrld's [shine ](https://github.com/vrld/shine)post processing shader effects to push?. An example or syntax will be helpful! I know there is a setShader function, but cannot get any result.

**Comment by Ulydev** [comment]
Hey cooljith91112, thanks for opening an issue. Sorry for the delay, I've been quite busy with school.

I've tried to play around with push and shine, and I've managed to get post-processing effects to work. Unfortunately, it seems like shine would need to be modified to have complete compatibility with push.

In the meantime, if you really want to use such effects, you could extract only the shaders and apply them with push.

I'll try to investigate the issue a bit further, but I can't guarantee anything.

**Comment by cooljith91112** [comment]
THANKS @Ulydev. I will try that.
