### ISSUE TITLE
Performance slowdown using w/ shaders (shine library)?

### ISSUE THREAD

**Issue by ianfitzpatrick** [Ulydev/push#10]
Hi, thanks so much for making this, it works flawlessly UNLESS I turn on shaders :(

I am using the [Shine Library](https://github.com/vrld/shine) to apply a few post processing effects. When I enable these effects, I have intermittent issues with my framerate dropping way way down. 

Sometimes it just sort of stutters, but other times everything starts slowing down. If I turn off the shader effects, everything is fine. If I turn the shader effects on, but turn off Push, everything is fine. It's only when both are enabled that I experience these slowdowns.

I'm attaching an example Love file where this behavior happens, maybe you can make some sense of this behavior, or it's a known thing with shaders? To re-create sometimes I have to quit/reload the game several times to trigger the issue, though often it manifests on first load.

FYI you can kick by hitting the space bar, sometimes it seems like actually doing something in game also triggers the slowdown.

[OurTeam.love.zip](https://github.com/Ulydev/push/files/809813/OurTeam.love.zip)

**Comment by Ulydev** [comment]
Hello ianfitzpatrick, thanks for opening an issue.

This is a known problem (https://github.com/Ulydev/push/issues/1) and unfortunately I can't find a way around it. Push has a setShader function, I recommend you take the shaders code from shine and apply them directly with push. Shine creates additional canvases under the hood, so the push+shine combination makes it only more graphics intensive.

I'll try to do something, but in the meantime you should consider working around that problem.

**Comment by ianfitzpatrick** [comment]
Okay thanks for getting back to me, I should have looked in closed issues! I'll try and manually apply the shaders instead through push like you mention, thanks.

**Comment by Ulydev** [comment]
Also worth mentioning, next update will have a canvas API that will allow you to create as many canvases as you want to apply different shaders.

**Comment by Ulydev** [comment]
@ianfitzpatrick , I've added the canvas and shader API. You might want to check out the new examples.

**Comment by ianfitzpatrick** [comment]
@Ulydev Thanks a ton, I got shaders working with the new code examples in the readme!

Just for the benefit of anyone who stumbled on this thread later, in the case of the Shine shaders they are sort of embedded inside of Lua code, so you can't just include them as they are not normal shader files. You have to extract the shader portion to a separate file.

**Comment by ianfitzpatrick** [comment]
Ah sorry one more question, is there a simple way to apply multiple shaders to one canvas? In Shine there was a chaining system, but push:setShader is not cumulative right, it's just "this is the active shader?" 

From what I read in love forums I think I need to setup some kind of multi-pass logic in my draw loop. But just want to make sure I'm not missing a simpler way from within push.

Thanks again.

**Comment by D0NM** [comment]
I use 3+ canvases
and apply different shaders to them.
Then I draw all the canvases on the main canvas (where I use the **push** lib)

on switching to the fullscreen mode I lose all my shaders (they stop working. I apply them, but I see no results).
I have to investigate the bug (my bug, probable).

Your conversation might give me more clues.

**Comment by Ulydev** [comment]
@ianfitzpatrick , you're right. push doesn't have a multi-pass system *yet*, but it should be fairly easy to implement. For now, it only supports drawing each canvas with 1 custom shader, then apply another shader to the final, combined render.
I'll keep you updated about it.

@D0NM , please open another issue so we can keep them organized (and give me some .love so I can help you further, the demo works fine even in fullscreen mode).

**Comment by ianfitzpatrick** [comment]
@Ulydev Cool, thanks much.
