### ISSUE TITLE
Add Multi-Pass Shader Support

### ISSUE THREAD

**Issue by ianfitzpatrick** [Ulydev/push#11]
Just dropping a note to say I'd still love to see this, support for applying shaders in multiple passes in conjunction with push.

As a reminder, we discussed this in another closed issue:

https://github.com/Ulydev/push/issues/10

**Comment by Ulydev** [comment]
Hello @ianfitzpatrick ,
Thanks for opening an issue!
Unfortunately, I'm very busy with school so I can't do anything right now; but feel free to submit a PR if you can find a solution to this.
Either way, I'll try to work on this when I have some free time.

**Comment by ianfitzpatrick** [comment]
Cool, thanks for letting me know!

**Comment by Ulydev** [comment]
added in 2c238f4e6ceee5ad4015ad1b38a789f93becf5ec
