### ISSUE TITLE
support for an smaller active area than the window, screensize

### ISSUE THREAD

**Issue by SiENcE** [Ulydev/push#12]
An technique to prevent dark letterboxes by pixelart game sis to draw a larger background on screen, as large as the screen in any size. But todo this you have to center the active gamearea on screen, when the windowsize or the screensizes are larger.

When i try to use push, and the nativ game size is smaller than the windowsizes, the active area is located on the top-right.

**Comment by Ulydev** [comment]
Hello @SiENcE , sorry for the delay.

I don't quite understand the problem you're having. Is this related to push, or is it more concerning game development practices in general ? Either way, I'd be happy to help if you can provide some more information, and/or a code sample.
