### ISSUE TITLE
love.window.setMode options are limited and reset defaults from say conf.lua

### ISSUE THREAD

**Issue by jakebesworth** [Ulydev/push#17]
The code:

```
  love.window.setMode(self._RWIDTH, self._RHEIGHT, {
    fullscreen = self._fullscreen,
    resizable = self._resizable,
    highdpi = self._highdpi
  })
```

Is meant to enable the options in the setupScreen API.

The issue is that conf.lua (or other ways to set these options) might set a bunch of options which are thrown out for the defaults when this chunk is called.

An example is vsync. Set vsync to 0 in conf.lua, and when Push is initialized, it will reset vsync back to 1.

Removing this chunk of code and allowing conf.lua to set the values works... as push still relies on those flags for other operations.

Not sure what the best approach to this problem is. One possible solution is to query for all properties for their current values: https://love2d.org/wiki/love.window.setMode and set those in that function.

**Comment by Ulydev** [comment]
Yup yup! Good idea, will do this as soon as possible 😄

**Comment by Ulydev** [comment]
Implemented love.window.updateMode in 7a0de986b7f0edcab6cd349df62c315135fc28a8
