### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by paolaguarasci** [Ulydev/push#20]
Only White screen with v0.3 on Mac 10.14 Beta

--- 
Same code and same config with v0.2 return this error

Error: push.lua:101: attempt to call field 'getPixelScale' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function 'getPixelScale'
        push.lua:101: in function 'initValues'
        push.lua:48: in function 'setupScreen'
        main.lua:47: in function 'load'
        [string "boot.lua"]:488: in function <[string "boot.lua"]:487>
        [C]: in function 'xpcall'
        [string "boot.lua"]:650: in function <[string "boot.lua"]:639>
        [C]: in function 'xpcall'

**Comment by Ulydev** [comment]
Hello there! Thanks for opening an issue.
Could you please provide more information? What does "Only White screen" mean?

> Error: push.lua:101: attempt to call field 'getPixelScale' (a nil value)

This is expected behaviour, v0.2 doesn't support LÖVE 11.

**Comment by Ulydev** [comment]
Please feel free to reopen :-)

**Comment by Manvi07** [comment]
Is there some way to run the same code with v0.2?
