### ISSUE TITLE
Properly scale love.graphics.circle?

### ISSUE THREAD

**Issue by jessemillar** [Ulydev/push#23]
I've got everything set up in my project to scale images and fonts properly, but I noticed today that `love.graphics.circle` and `love.graphics.ellipse` don't scale to the same pixel size as everything else. Is that a known bug/issue/design choice?

As an example, notice the gray circle in the top-left corner. Its pixels are about a third the size of the other pixels on screen.
<img width="834" alt="screen shot 2018-11-22 at 3 12 27 pm" src="https://user-images.githubusercontent.com/4627837/48922004-3308ed80-ee69-11e8-839a-ef9a6f323cba.png">

**Comment by jessemillar** [comment]
Fiddled around more tonight and found out that setting `highdpi = false` inside `push:setupScreen` fixed the problem. I falsely assumed that `highdpi` would default to `false` if unspecified.

**Comment by Ulydev** [comment]
Hello, thanks for using push. I will make sure to include the default flags in the documentation :-)
