### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by Spairkie** [Ulydev/push#24]
There is an issue with background color. I fixed it by commenting out line 182 in push:finish.
--love.graphics.setBackgroundColor(unpack(self._borderColor))
It was preventing me from setting a background color

Is my game going to do fine with that line out or that line is important. BTW thank you for your awesome library. C'est formidable

**Comment by Ulydev** [comment]
Hello @Spairkie,
You can set the background color using push:setBorderColor(r, g, b, a). It's nothing much, your game is going to do absolutely fine with or without that line. Please keep me updated about it! I would love to hear about your game, ami francophone !
