### ISSUE TITLE
Error push.lua:48 : bad argument # 2 to 'windowUpdateMode'(number expected, got table)

### ISSUE THREAD

**Issue by ghost** [Ulydev/push#34]
Please help me  I'm using push library in my project ..and i copied the code push.lua provided by you in push.lua file and when i run the program this error is expected on this line of code 
windowUpdateMode(self._RWIDTH, self._RHEIGHT, {
    fullscreen = self._fullscreen,
    resizable = self._resizable,
    highdpi = self._highdpi
  })
`function push:setupScreen(WWIDTH, WHEIGHT, RWIDTH, RHEIGHT, settings)

  settings = settings or {}

  self._WWIDTH, self._WHEIGHT = WWIDTH, WHEIGHT
  self._RWIDTH, self._RHEIGHT = RWIDTH, RHEIGHT

  self:applySettings(self.defaults) --set defaults first
  self:applySettings(settings) --then fill with custom settings
  
  windowUpdateMode(self._RWIDTH, self._RHEIGHT, {
    fullscreen = self._fullscreen,
    resizable = self._resizable,
    highdpi = self._highdpi
  })

  self:initValues()

  if self._canvas then
    self:setupCanvas({ "default" }) --setup canvas
  end

  self._borderColor = {0, 0, 0}

  self._drawFunctions = {
    ["start"] = self.start,
    ["end"] = self.finish
  }

  return self
end`

**Comment by Ulydev** [comment]
Hi @Empyre17 , thanks for using push. Could you please explain your issue more in detail? How do you use the library (are you calling a function? Show a relevant part of your code e.g. main.lua), what is the error you get?
edit: I'm guessing you called push:setupScreen with the wrong number of arguments, could you show me?

**Comment by ghost** [comment]
Im using the library on main.lua here the code
function love.load()
  push:setupScreen(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_HEIGHT, {  
    fullscreen = false,
    resizable = false,
    vsync = true
  })
end
and i have the other error on this segment of my code, it says that is
waiting for a number and got a table, but i really doesnt know how to fix
it, or Im thinking that  on the code of main.lua I´m using it wrong
 windowUpdateMode(self._RWIDTH, self._RHEIGHT, {
    fullscreen = self._fullscreen,
    resizable = self._resizable,
    highdpi = self._highdpi}
  )

**Comment by ghost** [comment]
I also send a email, but here is where I called push:setupScreen 
`push:setupScreen(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_HEIGHT, {
    fullscreen = false,
    resizable = false,
    vsync = true
  })`

**Comment by Ulydev** [comment]
I think you forgot to add the `WINDOW_WIDTH` argument in your code. The call to `push:setupScreen` should look like `(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_WIDTH, WINDOW_HEIGHT, { ... })`

**Comment by ghost** [comment]
Yep it was that, thats the beautiful of programing, lol a simple mistake can give you headaches, and btw thanks you are my hero
