### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by urmithakkar** [Ulydev/push#35]
Hi, while I run my code I am getting this error. Can you please help me out here. Thanks.
Error

push.lua:101: attempt to call field 'getPixelScale' (a nil value)

Traceback

push.lua:101: in function 'initValues'
push.lua:48: in function 'setupScreen'
main.lua:16: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

[push.docx](https://github.com/Ulydev/push/files/5213082/push.docx)

**Comment by Ecclessey** [comment]
In your main.lue is it possible you wrote: 

push.apply 

instead of:

push:apply

I had the same error and this fixed it.

**Comment by Ulydev** [comment]
Hi @urmithakkar 
Please see https://love2d.org/forums/viewtopic.php?t=86162
Thanks!
