### ISSUE TITLE
Error when running love, any help?

### ISSUE THREAD

**Issue by Wh0Kris** [Ulydev/push#37]
<img width="722" alt="Screen Shot 2020-09-25 at 8 25 52 PM" src="https://user-images.githubusercontent.com/71857211/94325639-53c29280-ff6d-11ea-960c-d7c0e27ba4d8.png">

**Comment by tekeoglan** [comment]
> <img width="722" alt="Screen Shot 2020-09-25 at 8 25 52 PM" src="https://user-images.githubusercontent.com/71857211/94325639-53c29280-ff6d-11ea-960c-d7c0e27ba4d8.png">
> 

If I'm truly remember set the hdpi "false" in push.lua,if doesn't work set all window setups false as default in push.lua

**Comment by Ulydev** [comment]
Hi @Wh0Kris  
Please see https://love2d.org/forums/viewtopic.php?t=86162
Thanks!
