### ISSUE TITLE
Border color

### ISSUE THREAD

**Issue by adean91** [Ulydev/push#4]
If you set love.graphics.setBackgroundColor( ) then the border color becomes that color, as opposed to the default/set color with push:setBorderColor().

**Comment by adean91** [comment]
After looking into your module, I see push:apply() has been depreciated. While using start() and finish() it works as expected. I suggest at least updating the README to reflect this, as it shows to use apply().

**Comment by Ulydev** [comment]
Thanks for the opening an issue! Fixed in 6f673f6de440e99a465ec32a7a8dc23d386d2117 .
