### ISSUE TITLE
push:setupScreen makes the program close

### ISSUE THREAD

**Issue by derek90** [Ulydev/push#43]
`push:setupScreen` is making the program close. I have the following files:

main.lua
```
push = require 'vendor/push'

love.window.setMode(0, 0, {
  fullscreen = true,
  vsync = -1
})
WINDOW_WIDTH, WINDOW_HEIGHT = love.graphics.getDimensions()
WINDOW_WIDTH = WINDOW_WIDTH/2
WINDOW_HEIGHT = WINDOW_HEIGHT/2

VIRTUAL_WIDTH = 432
VIRTUAL_HEIGHT = 243

function love.load()
  love.graphics.setDefaultFilter('nearest', 'nearest')

  push:setupScreen(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_WIDTH, WINDOW_HEIGHT, {
    fullscreen = false,
    resizable = false,
    highdpi = true
  })
end
```

conf.lua
```
function love.conf(t)
  t.window.width = 1280
  t.window.height = 720
  t.modules.joystick = false
  t.externalstorage = true
end
```

When running `love .` in the root folder, love opens but immediatly closes. If I comment the `push:setupScreen` function call, the program keeps opened

I'm using Love2d 11.3 (latest version at the moment) and my GPU is an AMD Radeon HD 8610G and its drivers are up to date

**Comment by derek90** [comment]
I just found what was causing the problem, without that vsync = -1 in
```
love.window.setMode(0, 0, {
  fullscreen = true,
  vsync = -1
})
```
worked

**Comment by Ulydev** [comment]
glad you got it figured out! just curious if you have seen this vsync = -1 somewhere? It should be a boolean. Good luck with your project!

**Comment by derek90** [comment]
Thanks!

Yes, in the Love2d official docs: https://love2d.org/wiki/love.window.setMode

It says:
"number vsync (1)
Enables or disables vertical synchronisation ('vsync'): 1 to enable vsync, 0 to disable it, and -1 to use adaptive vsync (where supported). Prior to 11.0 this was a boolean flag, rather than a number."

**Comment by Ulydev** [comment]
thanks - looks like I need to catch up 😅

**Comment by derek90** [comment]
I'm using it like this:
```
  push:setupScreen(VIRTUAL_WIDTH, VIRTUAL_HEIGHT, WINDOW_WIDTH, WINDOW_HEIGHT, {
    fullscreen = false,
    resizable = false,
    highdpi = true,
    vsync = -1
  })
```
And is not crashing. But I'm not sure if that means that the property works
I took a look to the push library source code, and I'm not sure if its using the old 11.0 version or the one I have (11.3)
```
local love11 = love.getVersion() == 11
local getDPI = love11 and love.window.getDPIScale or love.window.getPixelScale
local windowUpdateMode = love11 and love.window.updateMode or function(width, height, settings)
  local _, _, flags = love.window.getMode()
  for k, v in pairs(settings) do flags[k] = v end
  love.window.setMode(width, height, flags)
end
```
