### ISSUE TITLE
Full screen pixel-perfect mode request

### ISSUE THREAD

**Issue by D0NM** [Ulydev/push#5]
I'd like to have "pixel perfect" mode
where all the scaled pixels are squares: **1x1, 2x2, 3x3** and such.
Ofc, you'll have to leave some unused space (borders) at every side of the screen.

With our project I just cannot stand the pixels tearing. When scaled pixels have different width
you see bad tearing at the full screen mode.

**Comment by Ulydev** [comment]
hey there, thanks for the issue! fixed in 5f586e04565c15d628602b9fa79d526364673cdd
you can now provide a **pixelperfect** argument to push:setupScreen
