### ISSUE TITLE
Cut canvas on the 3rd(and the next) full screen switching

### ISSUE THREAD

**Issue by D0NM** [Ulydev/push#6]
The init:
```
GLOBAL_SETTING = {
    FULL_SCREEN = false,
    WINDOW_WIDTH = 640,
    WINDOW_HEIGHT = 480
}

    push:setupScreen(GLOBAL_SETTING.WINDOW_WIDTH, GLOBAL_SETTING.WINDOW_HEIGHT,
	GLOBAL_SETTING.WINDOW_WIDTH, GLOBAL_SETTING.WINDOW_HEIGHT,
        {fullscreen = GLOBAL_SETTING.FULL_SCREEN, resizable = false})

```
Usage:
`push:switchFullscreen()`
I get cut canvas after switching modes Window -> FullScreen -> Window -> FullScreen 
It looks like some values get broken.

**My workaround:**
```
	--this workaround makes PUSH lib switch full screen/window w/o problems
	--passing the constant screen resolution every time
    push:switchFullscreen(GLOBAL_SETTING.WINDOW_WIDTH,GLOBAL_SETTING.WINDOW_HEIGHT)
```

I use "push" in our open source game project Zabuyaki 
https://github.com/thomasgoldstein/zabuyaki
It is easy to check. Use **F11** to switch Windowed/FullScreen modes.
controls: **X key - Ok, C key - Cancel, Arrow keys**

**Comment by Ulydev** [comment]
fixed in 476290d9c8128cdd55756aecd66409712b16aa17
